### ISSUE TITLE
Can I use populate without authentication?

### ISSUE THREAD

**Issue by kieusonlam** [feathersjs/feathers-hooks#132]
I building a simple blog by using feathers, I want to get out post author infomation but it only work when I logged in. I want to everyone can get out that infomation without log in, what should I do? 

Here my hook:

```
'use strict';

const process = require('./process');

const globalHooks = require('../../../hooks');
const hooks = require('feathers-hooks');
const auth = require('feathers-authentication').hooks;

const populateAuthor = hooks.populate('authorInfo', {
  service: 'users',
  field: 'author'
});

exports.before = {
  all: [],
  find: [],
  get: [],
  create: [
    auth.verifyToken(),
    auth.populateUser(),
    auth.restrictToAuthenticated(),
    process()
  ],
  update: [
    auth.verifyToken(),
    auth.populateUser(),
    auth.restrictToAuthenticated()
  ],
  patch: [
    auth.verifyToken(),
    auth.populateUser(),
    auth.restrictToAuthenticated()
  ],
  remove: [
    auth.verifyToken(),
    auth.populateUser(),
    auth.restrictToAuthenticated()
  ]
};

exports.after = {
  all: [],
  find: [populateAuthor],
  get: [populateAuthor],
  create: [populateAuthor],
  update: [],
  patch: [],
  remove: []
};
```
I got this error
```
{ NotAuthenticated: Authentication token missing.
    at NotAuthenticated.ExtendableBuiltin (C:\Users\TOMORROW9\Desktop\vue-feathers-wepack\node_modules\feathers-errors\lib\index.js:21:28)
    at NotAuthenticated.FeathersError (C:\Users\TOMORROW9\Desktop\vue-feathers-wepack\node_modules\feathers-errors\lib\index.js:96:116)
    at new NotAuthenticated (C:\Users\TOMORROW9\Desktop\vue-feathers-wepack\node_modules\feathers-errors\lib\index.js:149:117)
    at Object.<anonymous> (C:\Users\TOMORROW9\Desktop\vue-feathers-wepack\node_modules\feathers-authentication\lib\hooks\verify-token.js:23:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  type: 'FeathersError',
  name: 'NotAuthenticated',
  code: 401,
  className: 'not-authenticated',
  data: undefined,
  errors: {} }
```

**Comment by marshallswain** [comment]
@kieusonlam You should only need to remove the `auth.restrictToAuthenticated()` hook from any endpoint that you want to be available without auth.

**Comment by kieusonlam** [comment]
@marshallswain Thanks for you advice, I did try that, it's still not work. 

Anyway I only use `auth.restrictToAuthenticated()` on `create, update, patch and remove` It's should not the problem.

In my project, I want Quest to see the blog posts but they cannot create new post so I believe that I did it right.

**Comment by marshallswain** [comment]
Ah.  I scrolled to the right on your posted stack trace.  The hook that's throwing the error is `verify-token.js:23:13`.  You'll have to track down where that hook is getting hit.

**Comment by daffl** [comment]
With auth 0.7 doesn't all of

```
    auth.verifyToken(),
    auth.populateUser(),
    auth.restrictToAuthenticated(),
```

have to be removed in order to remove the auth requirement?

**Comment by kieusonlam** [comment]
Thank you guys. It's work!
