### ISSUE TITLE
`__hooks` of existing service should not be overwritten

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-hooks#154]
Something like

```
app.use('/me/projects', app.service('/projects'))
```

Throws an error

```
Object.defineProperty(target, '__hooks', {
         ^
TypeError: Cannot redefine property: __hooks
```

Hooks should not try to redefine that object if it already exists.

**Comment by Mattchewone** [comment]
I thought i'd have a look into fixing it. 

I tried this:
```
  if (!target.hasOwnProperty('__hooks')) {
      Object.defineProperty(target, '__hooks', {
        value: {}
      });
  }
```
Which passed the tests, but trying it gave me this error, when calling that route:
```
projects - Method: find: 'params' is not a valid hook method
```
Other routes work fine, and when removing the call to 
```
app.use('/me/projects', app.service('/projects'))
```
It works fine the the `/projects` call.

**Comment by daffl** [comment]
I think the mixin in https://github.com/feathersjs/feathers-hooks/blob/master/src/hooks.js#L10 should just check if there is a `hooks` method

```js
function hookMixin (service) {
  if(typeof service.hooks === 'function') {
    return;
  }
```

**Comment by Mattchewone** [comment]
Thanks, I'll give that a go later and will make a PR.

**Comment by Versoo** [comment]
I have something like that:

`module.exports = function () {
  const app = this;
  const Model = createModel(app);
  const paginate = app.get('paginate');
  const options = {
    name: 'games',
    Model,
    paginate
  };
  app.use('/games', createService(options));
  const service = app.service('games');
  service.hooks(hooks);
  if (service.filter) {
    service.filter(filters);
  }
  app.use('/games/:gameId/players', app.service('users'));
};`

And when I use method GET, server returns me all users but in console I have error:

> Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/LearnNode/api/node_modules/express/lib/response.js:725:10)
    at Object.formatter.application/json (/LearnNode/api/node_modules/feathers-errors/lib/error-handler.js:69:13)
    at /LearnNode/api/node_modules/feathers-errors/lib/error-handler.js:86:36
    at Layer.handle_error (/LearnNode/api/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/LearnNode/api/node_modules/express/lib/router/index.js:315:13)
    at /LearnNode/api/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/LearnNode/api/node_modules/express/lib/router/index.js:335:12)
    at next (/LearnNode/api/node_modules/express/lib/router/index.js:275:10)
    at /LearnNode/api/node_modules/feathers-errors/lib/not-found-handler.js:9:5
    at Layer.handle [as handle_request] (/LearnNode/api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/LearnNode/api/node_modules/express/lib/router/index.js:317:13)
    at /LearnNode/api/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/LearnNode/api/node_modules/express/lib/router/index.js:335:12)
    at next (/LearnNode/api/node_modules/express/lib/router/index.js:275:10)
    at next (/LearnNode/api/node_modules/express/lib/router/route.js:127:14)
